### ISSUE TITLE
Share templates between Azure projects

### ISSUE THREAD

**Issue by ataylorme** [damienaicheh/XamarinReusablePipeline#1]
Hi @damienaicheh,
Thank you for the article https://damienaicheh.github.io/xamarin/azure/devops/2019/11/21/reuse-your-azure-devops-pipeline-en.html, it is really helpful. In the article you say:

> When you are satisfy with your differents templates, I recommend you to put all of them inside a specific repository so it will be reusable from any of your projects.

Can you explain that a bit more? For example, if you had a second repository similar to this one where would you place the templates so that you can maintain them on one place and have both Azure DevOps pipelines use them?

**Comment by damienaicheh** [comment]
Hi, you're welcome!

You can put them inside a specific Git repository inside Azure DevOps or inside Github directly.
I wrote another tutorial on this subject. Hope it will help you:
[https://damienaicheh.github.io/xamarin/azure/devops/2020/03/26/create-your-own-bank-of-templates-for-azure-devops-en.html](https://damienaicheh.github.io/xamarin/azure/devops/2020/03/26/create-your-own-bank-of-templates-for-azure-devops-en.html)

**Comment by ataylorme** [comment]
Yes, that helps a lot. Thank you! I'm impressed by Azure DevOps. It is a really mature platform compared to others.

**Comment by damienaicheh** [comment]
Yes, and so much cool stuff is coming soon!
